//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_WCF_REST_JSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimento_Refeicao
    {
        public int Id { get; set; }
        public int id_alimento { get; set; }
        public int id_refeicao { get; set; }
    
        public virtual AlimentoEntidade Alimento { get; set; }
        public virtual RefeicaoEntidade Refeicao { get; set; }
    }
}
