//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_WCF_REST_JSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlimentoEntidade
    {
        public int id { get; set; }
        public string nome { get; set; }
        public int grupo { get; set; }
        public Nullable<int> porcao { get; set; }
        public Nullable<double> valor_calorico { get; set; }
        public Nullable<double> cho { get; set; }
        public Nullable<double> proteinas { get; set; }
        public Nullable<double> gorduras_totais { get; set; }
        public Nullable<double> gorduras_saturadas { get; set; }
        public Nullable<double> colesterol { get; set; }
        public Nullable<double> fosforo { get; set; }
        public Nullable<double> poliinsaturados { get; set; }
        public Nullable<double> monoinsaturados { get; set; }
        public Nullable<double> vitamina_b1 { get; set; }
        public Nullable<double> vitamina_b2 { get; set; }
        public Nullable<double> vitamina_b3 { get; set; }
        public Nullable<double> vitamina_b6 { get; set; }
        public Nullable<double> gordura_trans { get; set; }
        public Nullable<double> fibra_alimentar { get; set; }
        public Nullable<double> acucar { get; set; }
        public Nullable<double> sodio { get; set; }
        public Nullable<double> selenio { get; set; }
        public Nullable<double> calcio { get; set; }
        public Nullable<double> ferro { get; set; }
        public Nullable<double> potassio { get; set; }
        public Nullable<double> zinco { get; set; }
        public Nullable<double> magnesio { get; set; }
        public Nullable<double> vitamina_a { get; set; }
        public Nullable<double> vitamina_b { get; set; }
        public Nullable<double> vitamina_c { get; set; }
        public Nullable<double> vitamina_d { get; set; }
        public Nullable<double> vitamina_e { get; set; }
        public Nullable<double> vitamina_b9 { get; set; }
        public Nullable<double> vitamina_b12 { get; set; }
    
        public virtual GrupoEntidade Grupo1 { get; set; }
    }
}
