//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_WCF_REST_JSON
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDemoEntities : DbContext
    {
        public MyDemoEntities()
            : base("name=MyDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductEntity> ProductEntities { get; set; }
        public virtual DbSet<AlimentoEntidade> AlimentoEntidades { get; set; }
        public virtual DbSet<GrupoEntidade> GrupoEntidades { get; set; }
        public virtual DbSet<Alimento_Refeicao> Alimento_Refeicao { get; set; }
        public virtual DbSet<RefeicaoEntidade> RefeicaoEntidades { get; set; }
    }
}
