//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_WCF_REST_JSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefeicaoEntidade
    {
        public RefeicaoEntidade()
        {
            this.Alimento_Refeicao = new HashSet<Alimento_Refeicao>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Alimento_Refeicao> Alimento_Refeicao { get; set; }
    }
}
